FROM node:18-alpine

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install --legacy-peer-deps
RUN npm install -g npm@latest
RUN apk add --no-cache git
COPY ./ .

EXPOSE 3000
CMD ["npm", "run", "dev"]
