services:
  frontend:
    build:
      context: ../app
      dockerfile: ../docker/Dockerfile.dev
    container_name: mane_front
    ports:
      - 5038:3000
    volumes:
      - ../app:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    restart: always
